### ISSUE TITLE
TypeError: Cannot call method 'call' of undefined

### ISSUE THREAD

**Issue by dialelo** [cemerick/clojurescript.test#80]
Hi and thanks for taking the time to port clojure.test to ClojureScript.

I recently added a test to a isomorphic Clj(s) library I'm working on and, even when it works without any problems in Clojure, I get the following error in ClojureScript:

```
ERROR in (test-core/test-lift-m) (:)
It can lift a function to a Monad Transformer
expected: (= [(maybe/just 1) (maybe/just 2) (maybe/just 3) (maybe/just 4) (maybe/just 5) (maybe/just 6)] (m/with-monad maybe-sequence-monad (monad+ [(maybe/just 0) (maybe/just 2) (maybe/just 4)] [(maybe/just 1) (maybe/just 2)])))
  actual:
TypeError: Cannot call method 'call' of undefined
    at eval (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:27121:120)
    at cemerick.cljs.test.test_function.c (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18723:17)
    at cemerick.cljs.test.test_function.a (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18747:18)
    at cljs.core.chunked_seq_QMARK_.call.k (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18785:61)
    at cemerick.cljs.test.default_fixture (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18596:12)
    at eval (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18783:240)
    at cemerick.cljs.test.default_fixture (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18596:12)
    at cemerick.cljs.test.test_all_vars.c (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18768:9)
    at cemerick.cljs.test.test_all_vars.a (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18810:18)
    at cemerick.cljs.test.test_ns.c (eval at <anonymous> (/tmp/node-runner2869039307250186175.js:37:76), <anonymous>:18827:80)
```

I'm clueless about what could be causing this, does it look like a clojurescript.test issue to you?

Thanks for your time.

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
